name: iOS CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      # 1. Descargar repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Configurar Xcode
      - name: Set up Xcode
        run: sudo xcode-select -s /Applications/Xcode.app

      # 3. Resolver dependencias (Swift Packages)
      - name: Resolve Swift Packages
        run: |
          xcodebuild -resolvePackageDependencies \
            -project AvanceProyecto.xcodeproj

      # 4. Compilar y correr tests en simulador con cobertura
      - name: Build and Test
        run: |
          xcodebuild test \
            -scheme AvanceProyecto \
            -project AvanceProyecto.xcodeproj \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 16' \
            ONLY_ACTIVE_ARCH=NO \
            -enableCodeCoverage YES

      # 5. Subir resultados de test como artefacto
      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: TestResults
          path: ~/Library/Developer/Xcode/DerivedData/**/Logs/Test/*.xcresult

      # 6. Subir cobertura a Codecov
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

