name: iOS CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Xcode
      run: sudo xcode-select -s /Applications/Xcode.app

    # 1. Build for testing
    - name: Build for testing
      run: xcodebuild build-for-testing \
        -scheme AvanceProyecto \
        -sdk iphonesimulator \
        -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.5'

    # 2. Run tests without rebuilding
    - name: Run tests
      run: xcodebuild test-without-building \
        -scheme AvanceProyecto \
        -sdk iphonesimulator \
        -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.5' \
        -enableCodeCoverage YES

    # 3. Ejecutar lane de Fastlane (opcional)
    - name: Run Fastlane CI lane
      run: fastlane ios ci
